network:
  interface: "ethernet"
  max_packets: 1000

anomaly_detection:
  contamination: 0.1
  n_estimators: 100
  retrain_interval: 3600

monitoring:
  alert_threshold: 0.8
  max_alerts_per_minute: 10
  metrics_interval: 60

security:
  encryption_enabled: true
  jwt_expiration: 3600
  min_password_length: 12

database:
  connection_string: "postgresql://ids_user:123@localhost:5432/ids_db"

logging:
  level: "INFO"
  file: "logs/cyber_defense.log"
  max_size: 10485760  # 10MB
  backup_count: 5 