version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1 