version: '3.8'

services:
  agent-manager:
    build: 
      context: ./agent-manager
      dockerfile: Dockerfile.rust
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      
  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile.rust
    depends_on:
      - kafka
      - elasticsearch
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000" 