network_interface: "Ethernet"
capture_duration: 60  # seconds

logging:
  level: INFO
  file: "logs/ids.log"

anomaly_detection:
  contamination: 0.1
  model_path: "models/anomaly_detector.joblib"

alert_system:
  critical_threshold: 0.8

database:
  connection_string: "postgresql://ids_user:123@localhost:5432/ids_db"

web_interface:
  host: "0.0.0.0"
  port: 5000